# coderprint's generated files, test code and line hashes. coderprint.py runs this file as part of one module, after
# the parts before it in PARTS, so it uses their names freely; it is not imported on its own.


GEN_LINES, GEN_HTML_LINES = 5, 40
# Generated files, known as GitHub's Linguist knows them, by what their first lines say rather than by their name:
# a comment that opens with a generator's mark within the first GEN_LINES lines ("// Code generated by sqlc. DO NOT
# EDIT.", "// <auto-generated />", "# Generated by Django 4.2", "# This file is auto-generated from the current state
# of the database", "/*! tailwindcss v3"), an HTML page whose first GEN_HTML_LINES lines name its generator (Hugo,
# Jekyll, Hexo, MkDocs, Javadoc, Doxygen), which with enough such pages makes every HTML, CSS and JavaScript file in
# their folder and below the site's output (generated_output), and a .ts file that is Qt Linguist's XML. A file that
# only mentions such words is not one, and neither is one whose comment only says not to edit something: "do not
# edit" marks a file only beside a word of generating.
SITE_PAGES, ROOT_SITE_PAGES = 3, 10
GEN_OPENERS = ("//", "#", "/*", "*", "--", ";", "<!--", "%", "{-", "(*", "<")
GENERATED = re.compile(r"(?:code generated|generated by|this (?:file|code) (?:is|was|has been) (?:auto-?|automatically "
                       r")?generated|this is (?:auto-?|code )?generated|auto-?generated|automatically generated|"
                       r"@generated|do not edit\b.*\bgenerat\w*|tailwindcss v\d)\b", re.I)
GENERATOR = re.compile(r"<meta\s[^>]*name=[\"']?generator\b|<!--\s*generated by\b", re.I)
WEB_OUTPUT = {"HTML", "CSS", "JavaScript"}


def generated_line(text, lang, n):
    """Whether line n, counted from 1, of a file in lang marks the whole file as generated (see GENERATED)."""
    s = text.lstrip().lstrip("﻿")
    if n <= GEN_LINES and s.startswith(GEN_OPENERS) and GENERATED.match(s.lstrip("/#*;!<{%(- \t")):
        return True
    if lang == "HTML" and n <= GEN_HTML_LINES and GENERATOR.search(s):
        return True
    return lang == "TypeScript" and n == 1 and s.startswith(("<?xml", "<!DOCTYPE TS", "<TS "))


def generated_head(get, n, lang):
    """Whether a file's first lines mark it as generated (generated_line)."""
    return any(generated_line(get(i), lang, i + 1) for i in range(min(n, GEN_HTML_LINES)))


def generated_output(paths, marked):
    """The paths among paths that are generated: those marked (a generator's mark in their first lines), and every
    HTML, CSS or JavaScript file of a generated site: under the deepest folder holding all the marked HTML pages that
    share a top-level folder, when there are at least SITE_PAGES of them (docs/ for docs/index.html, docs/404.html and
    docs/posts/a/index.html), or anywhere, when at least ROOT_SITE_PAGES marked pages include one at the top level (a
    site built into the root of owner.github.io). A page or two naming a generator, as a hand-written page copied from
    a template can, marks only itself, never the owner's scripts and styles beside it."""
    groups, pages = {}, 0
    for p in marked:
        if language_of(p) == "HTML":
            pages += 1
            folders = os.path.dirname(p).split("/") if "/" in p else []
            groups.setdefault(folders[0] if folders else "", []).append(folders)
    sites = {"/".join(os.path.commonprefix(folders)) for top, folders in groups.items()
             if top and len(folders) >= SITE_PAGES}
    if "" in groups and pages >= ROOT_SITE_PAGES:
        sites.add("")
    inside = lambda p: any(not s or p.startswith(s + "/") for s in sites)   # noqa: E731
    return {p for p in paths if p in marked or (sites and language_of(p) in WEB_OUTPUT and inside(p))}


def text_of(data):
    """A blob's text: UTF-16 or UTF-32 by its byte order mark (as Windows tools save PowerShell and resource
    scripts), else UTF-8, unless it holds a null byte in its first 8,000 bytes, which is how git tells a binary
    file; None for a binary file."""
    if data.startswith((b"\xff\xfe\x00\x00", b"\x00\x00\xfe\xff")):
        return data.decode("utf-32", "replace")
    if data.startswith((b"\xff\xfe", b"\xfe\xff")):
        return data.decode("utf-16", "replace")
    if b"\x00" in data[:8000]:
        return None
    return data.decode("utf-8", "replace")


def split_lines(data, sep):
    """A file's lines, as git counts them, and whether it ends with a newline."""
    lines = data.split(sep)
    if lines[-1]:
        return lines, False
    lines.pop()
    return lines, bool(lines)


# Test code, by where it lives: a folder of tests anywhere in the path, or a file named as one (test_x.py,
# x_test.go, x.test.ts, XTest.java, conftest.py, and this project's own xTEST.py); Rust's code compiled only in
# tests is found inside the files at the head (see rust_lines and rust_test_files).
TEST_DIRS = {"test", "tests", "__tests__", "__test__", "spec", "specs", "testing", "e2e", "integration_tests",
             "__mocks__", "mocks", "fixtures", "__fixtures__", "test_utils", "testutils", "testutil",
             "testhelpers", "testsupport", "cypress", "bench", "benches", "benchmark", "benchmarks"}
# A folder named for tests the way build tools name one: a word such as tests or IntegrationTests after a dot, dash
# or underscore (.NET's MyApp.Tests and MyApp.UnitTests, integration-tests, unit_tests), a source set in lower camel
# case ending in Test (Android's androidTest, Kotlin Multiplatform's commonTest), a camel-case name ending in Tests
# (Xcode's MyAppTests and MyAppUITests), or test and a capital (Gradle's testFixtures, testDebug). An app named
# SpeedTest and a pytest plugin's pytest_x package stay production.
TEST_DIR_WORD = re.compile(r"(?:x|rs|js|ts|go|e2e|unit|int|smoke|integration|functional|acceptance|system|ui)?tests?",
                           re.I)
TEST_DIR_CAMEL = re.compile(r"^[a-z][A-Za-z0-9]*[a-z0-9]Test$|[a-z0-9](?:UI)?Tests$|^test[A-Z]")
TEST_WORD = re.compile(r"^(?:x|rs|py|js|ts|go|e2e|unit|int|smoke)?tests?$|^conftest$", re.I)
CAMEL_TEST = re.compile(r"(?:[A-Za-z0-9](?:Test|Tests)|[a-z0-9]IT)\.[A-Za-z]+$")   # FooTest, IOTest, LoginUITests
# x.test.ts, and what test runners name their own: Cypress's x.cy.tsx, NestJS's x.e2e-spec.ts, tsd's x.test-d.ts
TEST_SUFFIX = re.compile(r"\.(?:test|cy|e2e-spec|e2e-test|test-d)\.[A-Za-z]+$", re.I)
# A file named as a spec (user_spec.rb, app.spec.ts, FooSpec.groovy) is a test only in the languages whose test
# frameworks name them so (RSpec, Jasmine, Mocha, busted, Spock, ScalaTest, Kotest, Quick, hspec, phpspec, ESpec);
# elsewhere spec.go, package_id_spec.rs, spec.py or KeySpec.java holds a specification, and is production
SPEC_LANGUAGES = {"Ruby", "JavaScript", "TypeScript", "CoffeeScript", "Lua", "Crystal", "Groovy", "Scala", "Kotlin",
                  "Swift", "Haskell", "PHP", "Elixir"}
SPEC_WORD = re.compile(r"^specs?$", re.I)
CAMEL_SPEC = re.compile(r"[a-z0-9]Spec\.[A-Za-z]+$")
SPEC_SUFFIX = re.compile(r"\.(?:spec|spec-d)\.[A-Za-z]+$", re.I)


@functools.lru_cache(maxsize=1 << 16)
def is_test(path, lang=None):
    """Whether a file is test code, by its folders and its name (see TEST_DIRS), in its language (see
    SPEC_LANGUAGES); lang is language_of(path) when not given."""
    parts = path.replace("\\", "/").split("/")
    if any(p.lower() in TEST_DIRS or TEST_DIR_CAMEL.search(p)
           or any(TEST_DIR_WORD.fullmatch(w) for w in re.split(r"[._\-]", p) if w) for p in parts[:-1]):
        return True
    name = parts[-1]
    words = [w for w in re.split(r"[_.\-]", name.split(".")[0]) if w]
    if CAMEL_TEST.search(name) or TEST_SUFFIX.search(name) or any(map(TEST_WORD.match, words)):
        return True
    return (lang or language_of(path)) in SPEC_LANGUAGES and bool(
        CAMEL_SPEC.search(name) or SPEC_SUFFIX.search(name) or any(map(SPEC_WORD.match, words)))


def line_hash(text):
    """A line's text with its whitespace collapsed, as a number that lasts only as long as this run."""
    return hash(" ".join(text.split()))


def limit():
    """How long a command may run: TIMEOUT, or less when the run's deadline is nearer (see time_left)."""
    try:
        left = time_left()
    except OutOfTime:
        raise OutOfTime("git was not started: the run is out of time") from None
    return TIMEOUT if left is None else min(TIMEOUT, left)
